name: Metrics

on:
  schedule: # Schedule to run every day
    - cron: '0 0 * * *'

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Metrics
      uses: lowlighter/metrics@latest
      with:
        token: ${{ secrets.METRICS_TOKEN }}
        user: cnf-hschoi # Replace with your GitHub username
        template: classic
        base: header, activity, community, repositories, skills, topics, traffic, isocalendar, streak, stars, pagespeed, posts, pullrequests, commits
        config_timezone: Asia/Seoul # Replace with your timezone
