name: Metrics

on:
  schedule: # Schedule to run every day
    - cron: '0 0 * * *'
  workflow_dispatch: {}

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Metrics
      uses: lowlighter/metrics@latest
      with:
        token: ${{ secrets.METRICS_TOKEN }}